"""Align imported script scenes to the real narration audio timeline.

The .docx package carries a *planned* timestamp per scene (estimated from a
words-per-minute pace at writing time). The actual narration — whether
generated by TTS or supplied as an external audio file — will not match
that pace exactly. This module derives each scene's *real* start/end time
by reusing the subtitle file already produced for the narration: MPT builds
subtitles as one entry per sentence, in narration order (see
``voice.create_subtitle`` / ``subtitle.create`` + ``subtitle.correct``), so
walking that subtitle file in the same per-sentence chunks used to split
each scene's narration text recovers each scene's real time range without
any new speech-alignment machinery.
"""

from typing import List

from loguru import logger

from app.models.schema import ScriptScene
from app.services import subtitle as subtitle_service
from app.utils import utils


def _srt_timestamp_to_seconds(value: str) -> float:
    value = value.strip()
    hours, minutes, rest = value.split(":")
    seconds, millis = rest.split(",")
    return (
        int(hours) * 3600
        + int(minutes) * 60
        + int(seconds)
        + int(millis) / 1000
    )


def _scene_line_count(narration: str) -> int:
    normalized = utils.normalize_script_for_subtitle_matching(narration)
    lines = [line for line in utils.split_string_by_punctuations(normalized) if line]
    return len(lines)


def align_scenes_to_subtitle(
    scenes: List[ScriptScene], subtitle_file: str
) -> List[ScriptScene]:
    """Fill in ``start_seconds``/``end_seconds`` on each scene from a subtitle file.

    The subtitle file is expected to hold one entry per sentence, in the
    same order as the narration (this is how MPT always builds it,
    regardless of whether the edge-tts or whisper provider produced it).
    Scenes whose text could not be confidently mapped are left with
    ``start_seconds``/``end_seconds`` unset (``None``) so callers can decide
    on a fallback (e.g. falling back to the docx's planned timestamps).
    """
    subtitle_items = subtitle_service.file_to_subtitles(subtitle_file)
    if not subtitle_items:
        logger.warning(
            f"no subtitle entries found in {subtitle_file}, cannot align scenes to audio"
        )
        return scenes

    total_items = len(subtitle_items)
    cursor = 0

    for scene in scenes:
        line_count = _scene_line_count(scene.narration)
        if line_count == 0:
            continue
        if cursor >= total_items:
            logger.warning(
                f"scene {scene.scene_id}: ran out of subtitle entries to align against "
                f"(subtitle has {total_items} entries), leaving unaligned"
            )
            continue

        start_index = cursor
        end_index = min(cursor + line_count, total_items) - 1
        cursor += line_count

        start_time_str = subtitle_items[start_index][1].split(" --> ")[0]
        end_time_str = subtitle_items[end_index][1].split(" --> ")[1]
        start_seconds = _srt_timestamp_to_seconds(start_time_str)
        end_seconds = _srt_timestamp_to_seconds(end_time_str)

        if end_seconds <= start_seconds:
            logger.warning(
                f"scene {scene.scene_id}: aligned to a zero/negative duration "
                f"({start_seconds}s -> {end_seconds}s), leaving unaligned"
            )
            continue

        scene.start_seconds = start_seconds
        scene.end_seconds = end_seconds

    if cursor < total_items:
        logger.debug(
            f"{total_items - cursor} trailing subtitle entries were not consumed by any scene"
        )

    return scenes


def finalize_scene_timeline(
    scenes: List[ScriptScene], audio_duration: float
) -> List[ScriptScene]:
    """Produce a complete, gapless, monotonic start/end timeline for every scene.

    ``align_scenes_to_subtitle`` is best-effort: some scenes may fail to
    align (e.g. the subtitle provider produced fewer entries than
    expected). This function guarantees every scene ends up with a usable
    ``start_seconds``/``end_seconds`` regardless of partial alignment
    failures, so it must run right before scenes are pinned to uploaded
    images:

    1. A baseline timeline is built by proportionally scaling each scene's
       ``planned_start_seconds`` (from the docx) against the real
       ``audio_duration`` — this is monotonic by construction, since the
       planned timestamps are already in narration order.
    2. Real aligned ``start_seconds`` (from ``align_scenes_to_subtitle``)
       override the baseline wherever available, clamped to never move
       backwards relative to the previous scene's resolved start.
    3. Each scene's ``end_seconds`` is set to the next scene's resolved
       start (or ``audio_duration`` for the last scene), so there are no
       gaps or overlaps between consecutive images.
    """
    if not scenes:
        return scenes

    last_planned = next(
        (s.planned_start_seconds for s in reversed(scenes) if s.planned_start_seconds is not None),
        None,
    )
    scale = (audio_duration / last_planned) if last_planned else None

    resolved_starts: List[float] = []
    previous_start = 0.0
    for i, scene in enumerate(scenes):
        if scale is not None and scene.planned_start_seconds is not None:
            baseline = scene.planned_start_seconds * scale
        else:
            # No usable planned timestamps at all: fall back to spreading
            # scenes evenly across the audio.
            baseline = audio_duration * i / len(scenes)

        resolved = scene.start_seconds if scene.start_seconds is not None else baseline
        resolved = max(0.0, min(resolved, audio_duration))
        resolved = max(resolved, previous_start)

        resolved_starts.append(resolved)
        previous_start = resolved

    for i, scene in enumerate(scenes):
        scene.start_seconds = resolved_starts[i]
        scene.end_seconds = (
            resolved_starts[i + 1] if i + 1 < len(scenes) else audio_duration
        )

    return scenes
